import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter,Poppins,Plus_Jakarta_Sans,DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/shared/widgets/header/Header";
import FooterPage from "@/shared/Modules/Footer/FooterPage";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter =Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plusjakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
   weight:["200","300","400","500","600","700","800",]
});

const dmsans = DM_Sans({
  variable: "--font-dm_sans",
  subsets: ["latin"],
   weight:["200","300","400","500","600","700","800",]
});


const poppeins = Poppins({
  variable: "--font-poppeins",
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800",]
});





export const metadata: Metadata = {
  title: "my pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppeins.variable} ${plusjakartaSans.variable} ${dmsans.variable}  antialiased  bg-[#00020D] w-full h-full`} 
      >
           <Header/>
        {children}
        <FooterPage />
  
      </body>
    </html>
  );
}
